import os
import sqlite3


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB_PATH = os.path.join(BASE_DIR, "data", "albaranes.db")
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()


class PostgresCursor:
    def __init__(self, cursor):
        self._cursor = cursor

    def execute(self, query, params=None):
        self._cursor.execute(query.replace("?", "%s"), params or ())
        return self

    def executemany(self, query, params):
        self._cursor.executemany(query.replace("?", "%s"), params)
        return self

    def fetchall(self):
        return self._cursor.fetchall()

    def fetchone(self):
        return self._cursor.fetchone()


class PostgresConnection:
    def __init__(self, connection):
        self._connection = connection

    def cursor(self):
        return PostgresCursor(self._connection.cursor())

    def execute(self, query, params=None):
        cursor = self.cursor()
        return cursor.execute(query, params)

    def executemany(self, query, params):
        cursor = self.cursor()
        return cursor.executemany(query, params)

    def commit(self):
        self._connection.commit()

    def close(self):
        self._connection.close()


def _postgres_columns(connection, table):
    cursor = connection.cursor()
    cursor.execute(
        """SELECT column_name FROM information_schema.columns
        WHERE table_schema='public' AND table_name=?""",
        (table,),
    )
    return {row[0] for row in cursor.fetchall()}


def _init_postgres(connection):
    cursor = connection.cursor()
    cursor.execute("""CREATE TABLE IF NOT EXISTS albaranes (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre TEXT, empresa TEXT, solicitado_por TEXT, materiales TEXT,
        comentario TEXT, envio_recogida TEXT, estado TEXT,
        observaciones TEXT, mensaje_final TEXT, fecha TEXT, foto_preparacion TEXT
    )""")
    cursor.execute("""CREATE TABLE IF NOT EXISTS equipos (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre TEXT NOT NULL, cantidad INTEGER NOT NULL, numero_serie TEXT NOT NULL,
        seccion TEXT NOT NULL, fecha_alta TEXT NOT NULL
    )""")
    cursor.execute("""CREATE TABLE IF NOT EXISTS reparaciones (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        fecha_entrada TEXT NOT NULL, empresa TEXT NOT NULL, reparacion TEXT NOT NULL,
        piezas_pendientes TEXT, presupuesto_monto REAL, presupuesto_archivo TEXT,
        estado TEXT NOT NULL DEFAULT 'en reparacion', fotos TEXT,
        fecha_finalizacion TEXT, presupuesto_estado TEXT DEFAULT 'pendiente'
    )""")
    if "foto_preparacion" not in _postgres_columns(connection, "albaranes"):
        cursor.execute("ALTER TABLE albaranes ADD COLUMN foto_preparacion TEXT")
    if "presupuesto_estado" not in _postgres_columns(connection, "reparaciones"):
        cursor.execute("ALTER TABLE reparaciones ADD COLUMN presupuesto_estado TEXT DEFAULT 'pendiente'")
    connection.commit()


def _init_sqlite(connection):
    cur = connection.cursor()
    cur.execute("""CREATE TABLE IF NOT EXISTS albaranes (
        id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT, empresa TEXT,
        solicitado_por TEXT, materiales TEXT, comentario TEXT,
        envio_recogida TEXT, estado TEXT, observaciones TEXT,
        mensaje_final TEXT, fecha TEXT, foto_preparacion TEXT
    )""")
    columns = {row[1] for row in cur.execute("PRAGMA table_info(albaranes)").fetchall()}
    if "foto_preparacion" not in columns:
        cur.execute("ALTER TABLE albaranes ADD COLUMN foto_preparacion TEXT")
    cur.execute("""CREATE TABLE IF NOT EXISTS equipos (
        id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT NOT NULL,
        cantidad INTEGER NOT NULL, numero_serie TEXT NOT NULL,
        seccion TEXT NOT NULL, fecha_alta TEXT NOT NULL
    )""")
    cur.execute("""CREATE TABLE IF NOT EXISTS reparaciones (
        id INTEGER PRIMARY KEY AUTOINCREMENT, fecha_entrada TEXT NOT NULL,
        empresa TEXT NOT NULL, reparacion TEXT NOT NULL, piezas_pendientes TEXT,
        presupuesto_monto REAL, presupuesto_archivo TEXT,
        estado TEXT NOT NULL DEFAULT 'en reparacion', fotos TEXT,
        fecha_finalizacion TEXT
    )""")
    columns = {row[1] for row in cur.execute("PRAGMA table_info(reparaciones)").fetchall()}
    if "presupuesto_estado" not in columns:
        cur.execute("ALTER TABLE reparaciones ADD COLUMN presupuesto_estado TEXT DEFAULT 'pendiente'")
    connection.commit()


def get_conn():
    if DATABASE_URL:
        import psycopg2

        connection = PostgresConnection(psycopg2.connect(DATABASE_URL))
        _init_postgres(connection)
        return connection

    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    connection = sqlite3.connect(DB_PATH, check_same_thread=False)
    _init_sqlite(connection)
    return connection


def init_db():
    conn = get_conn()
    conn.close()
