import os
import sqlite3


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB_PATH = os.path.join(BASE_DIR, "data", "albaranes.db")
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()


class PostgresCursor:
    def __init__(self, cursor):
        self._cursor = cursor

    def execute(self, query, params=None):
        self._cursor.execute(query.replace("?", "%s"), params or ())
        return self

    def executemany(self, query, params):
        self._cursor.executemany(query.replace("?", "%s"), params)
        return self

    def fetchall(self):
        return self._cursor.fetchall()

    def fetchone(self):
        return self._cursor.fetchone()


class PostgresConnection:
    def __init__(self, connection):
        self._connection = connection

    def cursor(self):
        return PostgresCursor(self._connection.cursor())

    def execute(self, query, params=None):
        cursor = self.cursor()
        return cursor.execute(query, params)

    def executemany(self, query, params):
        cursor = self.cursor()
        return cursor.executemany(query, params)

    def commit(self):
        self._connection.commit()

    def close(self):
        self._connection.close()


def _postgres_columns(connection, table):
    cursor = connection.cursor()
    cursor.execute(
        """SELECT column_name FROM information_schema.columns
        WHERE table_schema='public' AND table_name=?""",
        (table,),
    )
    return {row[0] for row in cursor.fetchall()}


def _init_postgres(connection):
    cursor = connection.cursor()
    cursor.execute("""CREATE TABLE IF NOT EXISTS albaranes (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre TEXT, empresa TEXT, solicitado_por TEXT, materiales TEXT,
        comentario TEXT, envio_recogida TEXT, estado TEXT,
        observaciones TEXT, mensaje_final TEXT, fecha TEXT, foto_preparacion TEXT,
        numero_serie TEXT
    )""")
    cursor.execute("""CREATE TABLE IF NOT EXISTS equipos (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre TEXT NOT NULL, cantidad INTEGER NOT NULL, numero_serie TEXT NOT NULL,
        seccion TEXT NOT NULL, fecha_alta TEXT NOT NULL
    )""")
    cursor.execute("""CREATE TABLE IF NOT EXISTS reparaciones (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        fecha_entrada TEXT NOT NULL, empresa TEXT NOT NULL, reparacion TEXT NOT NULL,
        piezas_pendientes TEXT, presupuesto_monto REAL, presupuesto_archivo TEXT,
        estado TEXT NOT NULL DEFAULT 'en reparacion', fotos TEXT,
        fecha_finalizacion TEXT, presupuesto_estado TEXT DEFAULT 'pendiente'
    )""")
    cursor.execute("""CREATE TABLE IF NOT EXISTS albaranes_finalizados (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        albaran_id INTEGER NOT NULL, fecha TEXT, nombre TEXT, empresa TEXT,
        solicitado_por TEXT, material TEXT, unidades TEXT,
        UNIQUE (albaran_id, material, unidades)
    )""")
    cursor.execute("""CREATE TABLE IF NOT EXISTS almacen_secciones (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre TEXT NOT NULL UNIQUE, descripcion TEXT, filas INTEGER NOT NULL DEFAULT 1,
        columnas INTEGER NOT NULL DEFAULT 1, alto_m REAL NOT NULL DEFAULT 2.5,
        ancho_m REAL NOT NULL DEFAULT 10, fondo_m REAL NOT NULL DEFAULT 10,
        capacidad_palets INTEGER NOT NULL DEFAULT 1, activa INTEGER NOT NULL DEFAULT 1
    )""")
    cursor.execute("""CREATE TABLE IF NOT EXISTS almacen_ubicaciones (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        seccion_id INTEGER NOT NULL, codigo TEXT NOT NULL UNIQUE, fila INTEGER NOT NULL,
        columna INTEGER NOT NULL, capacidad_palets INTEGER NOT NULL DEFAULT 1,
        alto_m REAL NOT NULL DEFAULT 2.5, ancho_m REAL NOT NULL DEFAULT 1.2,
        fondo_m REAL NOT NULL DEFAULT 1.2, activa INTEGER NOT NULL DEFAULT 1,
        FOREIGN KEY (seccion_id) REFERENCES almacen_secciones(id)
    )""")
    cursor.execute("""CREATE TABLE IF NOT EXISTS almacen_stock (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ubicacion_id INTEGER NOT NULL, material TEXT NOT NULL,
        codigo_material TEXT NOT NULL DEFAULT '', palets INTEGER NOT NULL DEFAULT 0,
        unidades_por_palet INTEGER NOT NULL DEFAULT 1, unidades_sueltas INTEGER NOT NULL DEFAULT 0,
        actualizado TEXT NOT NULL, UNIQUE (ubicacion_id, material, codigo_material),
        FOREIGN KEY (ubicacion_id) REFERENCES almacen_ubicaciones(id)
    )""")
    cursor.execute("""CREATE TABLE IF NOT EXISTS almacen_movimientos (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        fecha TEXT NOT NULL, tipo TEXT NOT NULL, ubicacion_id INTEGER NOT NULL,
        material TEXT NOT NULL, codigo_material TEXT NOT NULL DEFAULT '', palets INTEGER NOT NULL DEFAULT 0,
        unidades_por_palet INTEGER NOT NULL DEFAULT 1, unidades_sueltas INTEGER NOT NULL DEFAULT 0,
        referencia TEXT, albaran_id INTEGER, FOREIGN KEY (ubicacion_id) REFERENCES almacen_ubicaciones(id)
    )""")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_almacen_stock_ubicacion ON almacen_stock(ubicacion_id)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_almacen_movimientos_fecha ON almacen_movimientos(fecha)")
    if "foto_preparacion" not in _postgres_columns(connection, "albaranes"):
        cursor.execute("ALTER TABLE albaranes ADD COLUMN foto_preparacion TEXT")
    if "numero_serie" not in _postgres_columns(connection, "albaranes"):
        cursor.execute("ALTER TABLE albaranes ADD COLUMN numero_serie TEXT")
    if "presupuesto_estado" not in _postgres_columns(connection, "reparaciones"):
        cursor.execute("ALTER TABLE reparaciones ADD COLUMN presupuesto_estado TEXT DEFAULT 'pendiente'")
    connection.commit()


def _init_sqlite(connection):
    cur = connection.cursor()
    cur.execute("""CREATE TABLE IF NOT EXISTS albaranes (
        id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT, empresa TEXT,
        solicitado_por TEXT, materiales TEXT, comentario TEXT,
        envio_recogida TEXT, estado TEXT, observaciones TEXT,
        mensaje_final TEXT, fecha TEXT, foto_preparacion TEXT, numero_serie TEXT
    )""")
    columns = {row[1] for row in cur.execute("PRAGMA table_info(albaranes)").fetchall()}
    if "foto_preparacion" not in columns:
        cur.execute("ALTER TABLE albaranes ADD COLUMN foto_preparacion TEXT")
    if "numero_serie" not in columns:
        cur.execute("ALTER TABLE albaranes ADD COLUMN numero_serie TEXT")
    cur.execute("""CREATE TABLE IF NOT EXISTS equipos (
        id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT NOT NULL,
        cantidad INTEGER NOT NULL, numero_serie TEXT NOT NULL,
        seccion TEXT NOT NULL, fecha_alta TEXT NOT NULL
    )""")
    cur.execute("""CREATE TABLE IF NOT EXISTS reparaciones (
        id INTEGER PRIMARY KEY AUTOINCREMENT, fecha_entrada TEXT NOT NULL,
        empresa TEXT NOT NULL, reparacion TEXT NOT NULL, piezas_pendientes TEXT,
        presupuesto_monto REAL, presupuesto_archivo TEXT,
        estado TEXT NOT NULL DEFAULT 'en reparacion', fotos TEXT,
        fecha_finalizacion TEXT
    )""")
    cur.execute("""CREATE TABLE IF NOT EXISTS albaranes_finalizados (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        albaran_id INTEGER NOT NULL, fecha TEXT, nombre TEXT, empresa TEXT,
        solicitado_por TEXT, material TEXT, unidades TEXT,
        UNIQUE (albaran_id, material, unidades)
    )""")
    cur.execute("""CREATE TABLE IF NOT EXISTS almacen_secciones (
        id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT NOT NULL UNIQUE,
        descripcion TEXT, filas INTEGER NOT NULL DEFAULT 1, columnas INTEGER NOT NULL DEFAULT 1,
        alto_m REAL NOT NULL DEFAULT 2.5, ancho_m REAL NOT NULL DEFAULT 10,
        fondo_m REAL NOT NULL DEFAULT 10, capacidad_palets INTEGER NOT NULL DEFAULT 1,
        activa INTEGER NOT NULL DEFAULT 1
    )""")
    cur.execute("""CREATE TABLE IF NOT EXISTS almacen_ubicaciones (
        id INTEGER PRIMARY KEY AUTOINCREMENT, seccion_id INTEGER NOT NULL,
        codigo TEXT NOT NULL UNIQUE, fila INTEGER NOT NULL, columna INTEGER NOT NULL,
        capacidad_palets INTEGER NOT NULL DEFAULT 1, alto_m REAL NOT NULL DEFAULT 2.5,
        ancho_m REAL NOT NULL DEFAULT 1.2, fondo_m REAL NOT NULL DEFAULT 1.2,
        activa INTEGER NOT NULL DEFAULT 1, FOREIGN KEY (seccion_id) REFERENCES almacen_secciones(id)
    )""")
    cur.execute("""CREATE TABLE IF NOT EXISTS almacen_stock (
        id INTEGER PRIMARY KEY AUTOINCREMENT, ubicacion_id INTEGER NOT NULL,
        material TEXT NOT NULL, codigo_material TEXT NOT NULL DEFAULT '', palets INTEGER NOT NULL DEFAULT 0,
        unidades_por_palet INTEGER NOT NULL DEFAULT 1, unidades_sueltas INTEGER NOT NULL DEFAULT 0,
        actualizado TEXT NOT NULL, UNIQUE (ubicacion_id, material, codigo_material),
        FOREIGN KEY (ubicacion_id) REFERENCES almacen_ubicaciones(id)
    )""")
    cur.execute("""CREATE TABLE IF NOT EXISTS almacen_movimientos (
        id INTEGER PRIMARY KEY AUTOINCREMENT, fecha TEXT NOT NULL, tipo TEXT NOT NULL,
        ubicacion_id INTEGER NOT NULL, material TEXT NOT NULL, codigo_material TEXT NOT NULL DEFAULT '',
        palets INTEGER NOT NULL DEFAULT 0, unidades_por_palet INTEGER NOT NULL DEFAULT 1,
        unidades_sueltas INTEGER NOT NULL DEFAULT 0, referencia TEXT, albaran_id INTEGER,
        FOREIGN KEY (ubicacion_id) REFERENCES almacen_ubicaciones(id)
    )""")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_almacen_stock_ubicacion ON almacen_stock(ubicacion_id)")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_almacen_movimientos_fecha ON almacen_movimientos(fecha)")
    columns = {row[1] for row in cur.execute("PRAGMA table_info(reparaciones)").fetchall()}
    if "presupuesto_estado" not in columns:
        cur.execute("ALTER TABLE reparaciones ADD COLUMN presupuesto_estado TEXT DEFAULT 'pendiente'")
    connection.commit()


def get_conn():
    if DATABASE_URL:
        import psycopg2

        connection = PostgresConnection(psycopg2.connect(DATABASE_URL))
        _init_postgres(connection)
        return connection

    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    connection = sqlite3.connect(DB_PATH, check_same_thread=False)
    _init_sqlite(connection)
    return connection


def init_db():
    conn = get_conn()
    conn.close()
