import os
import sqlite3
import threading


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB_PATH = os.path.join(BASE_DIR, "data", "albaranes.db")
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
_DB_INITIALIZED = False
_DB_INIT_LOCK = threading.Lock()

DEFAULT_ALMACEN_SECCIONES = (
    [f"S{i}" for i in range(1, 31)]
    + [f"ELE{i}" for i in range(1, 4)]
    + [f"Z{i}" for i in range(1, 12)]
    + [f"STOCK{i}" for i in range(1, 7)]
    + [f"ESTA{i}" for i in range(1, 5)]
    + [f"ESTB{i}" for i in range(1, 5)]
    + [f"SP{fila}{letra}" for fila in range(1, 5) for letra in "ABCD"]
    + [
        "A1", "A2", "B1", "B2", "B3", "C1", "C2", "C3",
        "D1", "D2", "D3", "E1", "E2", "E3", "F1", "F2", "F3",
        "G2", "G3", "H2", "H3", "I2", "I3", "J2", "J3", "K2", "K3",
    ]
)

class PostgresCursor:
    def __init__(self, cursor):
        self._cursor = cursor

    def execute(self, query, params=None):
        self._cursor.execute(query.replace("?", "%s"), params or ())
        return self

    def executemany(self, query, params):
        self._cursor.executemany(query.replace("?", "%s"), params)
        return self

    def fetchall(self):
        return self._cursor.fetchall()

    def fetchone(self):
        return self._cursor.fetchone()


class PostgresConnection:
    def __init__(self, connection):
        self._connection = connection

    def cursor(self):
        return PostgresCursor(self._connection.cursor())

    def execute(self, query, params=None):
        cursor = self.cursor()
        return cursor.execute(query, params)

    def executemany(self, query, params):
        cursor = self.cursor()
        return cursor.executemany(query, params)

    def commit(self):
        self._connection.commit()

    def close(self):
        self._connection.close()

def _seed_almacen_secciones(connection):
    secciones_existentes = {
        fila[1]: fila[0]
        for fila in connection.execute("SELECT id, nombre FROM almacen_secciones").fetchall()
    }
    huecos = {
        "A1", "A2", "B1", "B2", "B3", "C1", "C2", "C3",
        "D1", "D2", "D3", "E1", "E2", "E3", "F1", "F2", "F3",
        "G2", "G3", "H2", "H3", "I2", "I3", "J2", "J3", "K2", "K3",
    }
    nuevas_secciones = [
        (nombre, 'Estanterias "Huecos"' if nombre in huecos else "")
        for nombre in DEFAULT_ALMACEN_SECCIONES
        if nombre not in secciones_existentes
    ]
    if nuevas_secciones:
        valores = ", ".join(
            "(?, ?, 1, 1, 2.5, 1.2, 1.2, 1)" for _ in nuevas_secciones
        )
        parametros = tuple(valor for seccion in nuevas_secciones for valor in seccion)
        connection.execute(
            "INSERT INTO almacen_secciones "
            "(nombre, descripcion, filas, columnas, alto_m, ancho_m, fondo_m, capacidad_palets) "
            f"VALUES {valores}",
            parametros,
        )
        secciones_existentes = {
            fila[1]: fila[0]
            for fila in connection.execute("SELECT id, nombre FROM almacen_secciones").fetchall()
        }

    ubicaciones_existentes = {
        fila[0]
        for fila in connection.execute("SELECT codigo FROM almacen_ubicaciones").fetchall()
    }
    nuevas_ubicaciones = [
        (secciones_existentes[nombre], f"{nombre}-R01-C01")
        for nombre in DEFAULT_ALMACEN_SECCIONES
        if f"{nombre}-R01-C01" not in ubicaciones_existentes
    ]
    if nuevas_ubicaciones:
        valores = ", ".join(
            "(?, ?, 1, 1, 1, 2.5, 1.2, 1.2)" for _ in nuevas_ubicaciones
        )
        parametros = tuple(valor for ubicacion in nuevas_ubicaciones for valor in ubicacion)
        connection.execute(
            "INSERT INTO almacen_ubicaciones "
            "(seccion_id, codigo, fila, columna, capacidad_palets, alto_m, ancho_m, fondo_m) "
            f"VALUES {valores}",
            parametros,
        )


def _postgres_columns(connection, table):
    cursor = connection.cursor()
    cursor.execute(
        """SELECT column_name FROM information_schema.columns
        WHERE table_schema='public' AND table_name=?""",
        (table,),
    )
    return {row[0] for row in cursor.fetchall()}


def _init_postgres(connection):
    cursor = connection.cursor()
    cursor.execute("""CREATE TABLE IF NOT EXISTS albaranes (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre TEXT, empresa TEXT, solicitado_por TEXT, materiales TEXT,
        comentario TEXT, envio_recogida TEXT, estado TEXT,
        observaciones TEXT, mensaje_final TEXT, fecha TEXT, foto_preparacion TEXT,
        numero_serie TEXT
    )""")
    cursor.execute("""CREATE TABLE IF NOT EXISTS equipos (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre TEXT NOT NULL, cantidad INTEGER NOT NULL, numero_serie TEXT NOT NULL,
        seccion TEXT NOT NULL, fecha_alta TEXT NOT NULL
    )""")
    cursor.execute("""CREATE TABLE IF NOT EXISTS albaranes_finalizados (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        albaran_id INTEGER NOT NULL, fecha TEXT, nombre TEXT, empresa TEXT,
        solicitado_por TEXT, material TEXT, unidades TEXT,
        UNIQUE (albaran_id, material, unidades)
    )""")
    cursor.execute("""CREATE TABLE IF NOT EXISTS almacen_secciones (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre TEXT NOT NULL UNIQUE, descripcion TEXT, filas INTEGER NOT NULL DEFAULT 1,
        columnas INTEGER NOT NULL DEFAULT 1, alto_m REAL NOT NULL DEFAULT 2.5,
        ancho_m REAL NOT NULL DEFAULT 10, fondo_m REAL NOT NULL DEFAULT 10,
        capacidad_palets INTEGER NOT NULL DEFAULT 1, activa INTEGER NOT NULL DEFAULT 1
    )""")
    cursor.execute("""CREATE TABLE IF NOT EXISTS almacen_ubicaciones (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        seccion_id INTEGER NOT NULL, codigo TEXT NOT NULL UNIQUE, fila INTEGER NOT NULL,
        columna INTEGER NOT NULL, capacidad_palets INTEGER NOT NULL DEFAULT 1,
        alto_m REAL NOT NULL DEFAULT 2.5, ancho_m REAL NOT NULL DEFAULT 1.2,
        fondo_m REAL NOT NULL DEFAULT 1.2, activa INTEGER NOT NULL DEFAULT 1,
        FOREIGN KEY (seccion_id) REFERENCES almacen_secciones(id)
    )""")
    cursor.execute("""CREATE TABLE IF NOT EXISTS almacen_stock (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ubicacion_id INTEGER NOT NULL, material TEXT NOT NULL,
        codigo_material TEXT NOT NULL DEFAULT '', palets INTEGER NOT NULL DEFAULT 0,
        unidades_por_palet INTEGER NOT NULL DEFAULT 1, unidades_sueltas INTEGER NOT NULL DEFAULT 0,
        actualizado TEXT NOT NULL, UNIQUE (ubicacion_id, material, codigo_material),
        FOREIGN KEY (ubicacion_id) REFERENCES almacen_ubicaciones(id)
    )""")
    cursor.execute("""CREATE TABLE IF NOT EXISTS almacen_movimientos (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        fecha TEXT NOT NULL, tipo TEXT NOT NULL, ubicacion_id INTEGER NOT NULL,
        material TEXT NOT NULL, codigo_material TEXT NOT NULL DEFAULT '', palets INTEGER NOT NULL DEFAULT 0,
        unidades_por_palet INTEGER NOT NULL DEFAULT 1, unidades_sueltas INTEGER NOT NULL DEFAULT 0,
        referencia TEXT, albaran_id INTEGER, FOREIGN KEY (ubicacion_id) REFERENCES almacen_ubicaciones(id)
    )""")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_almacen_stock_ubicacion ON almacen_stock(ubicacion_id)")
    cursor.execute("CREATE INDEX IF NOT EXISTS idx_almacen_movimientos_fecha ON almacen_movimientos(fecha)")
    if "foto_preparacion" not in _postgres_columns(connection, "albaranes"):
        cursor.execute("ALTER TABLE albaranes ADD COLUMN foto_preparacion TEXT")
    if "numero_serie" not in _postgres_columns(connection, "albaranes"):
        cursor.execute("ALTER TABLE albaranes ADD COLUMN numero_serie TEXT")
    _seed_almacen_secciones(connection)
    connection.commit()


def _init_sqlite(connection):
    cur = connection.cursor()
    cur.execute("""CREATE TABLE IF NOT EXISTS albaranes (
        id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT, empresa TEXT,
        solicitado_por TEXT, materiales TEXT, comentario TEXT,
        envio_recogida TEXT, estado TEXT, observaciones TEXT,
        mensaje_final TEXT, fecha TEXT, foto_preparacion TEXT, numero_serie TEXT
    )""")
    columns = {row[1] for row in cur.execute("PRAGMA table_info(albaranes)").fetchall()}
    if "foto_preparacion" not in columns:
        cur.execute("ALTER TABLE albaranes ADD COLUMN foto_preparacion TEXT")
    if "numero_serie" not in columns:
        cur.execute("ALTER TABLE albaranes ADD COLUMN numero_serie TEXT")
    cur.execute("""CREATE TABLE IF NOT EXISTS equipos (
        id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT NOT NULL,
        cantidad INTEGER NOT NULL, numero_serie TEXT NOT NULL,
        seccion TEXT NOT NULL, fecha_alta TEXT NOT NULL
    )""")
    cur.execute("""CREATE TABLE IF NOT EXISTS albaranes_finalizados (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        albaran_id INTEGER NOT NULL, fecha TEXT, nombre TEXT, empresa TEXT,
        solicitado_por TEXT, material TEXT, unidades TEXT,
        UNIQUE (albaran_id, material, unidades)
    )""")
    cur.execute("""CREATE TABLE IF NOT EXISTS almacen_secciones (
        id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT NOT NULL UNIQUE,
        descripcion TEXT, filas INTEGER NOT NULL DEFAULT 1, columnas INTEGER NOT NULL DEFAULT 1,
        alto_m REAL NOT NULL DEFAULT 2.5, ancho_m REAL NOT NULL DEFAULT 10,
        fondo_m REAL NOT NULL DEFAULT 10, capacidad_palets INTEGER NOT NULL DEFAULT 1,
        activa INTEGER NOT NULL DEFAULT 1
    )""")
    cur.execute("""CREATE TABLE IF NOT EXISTS almacen_ubicaciones (
        id INTEGER PRIMARY KEY AUTOINCREMENT, seccion_id INTEGER NOT NULL,
        codigo TEXT NOT NULL UNIQUE, fila INTEGER NOT NULL, columna INTEGER NOT NULL,
        capacidad_palets INTEGER NOT NULL DEFAULT 1, alto_m REAL NOT NULL DEFAULT 2.5,
        ancho_m REAL NOT NULL DEFAULT 1.2, fondo_m REAL NOT NULL DEFAULT 1.2,
        activa INTEGER NOT NULL DEFAULT 1, FOREIGN KEY (seccion_id) REFERENCES almacen_secciones(id)
    )""")
    cur.execute("""CREATE TABLE IF NOT EXISTS almacen_stock (
        id INTEGER PRIMARY KEY AUTOINCREMENT, ubicacion_id INTEGER NOT NULL,
        material TEXT NOT NULL, codigo_material TEXT NOT NULL DEFAULT '', palets INTEGER NOT NULL DEFAULT 0,
        unidades_por_palet INTEGER NOT NULL DEFAULT 1, unidades_sueltas INTEGER NOT NULL DEFAULT 0,
        actualizado TEXT NOT NULL, UNIQUE (ubicacion_id, material, codigo_material),
        FOREIGN KEY (ubicacion_id) REFERENCES almacen_ubicaciones(id)
    )""")
    cur.execute("""CREATE TABLE IF NOT EXISTS almacen_movimientos (
        id INTEGER PRIMARY KEY AUTOINCREMENT, fecha TEXT NOT NULL, tipo TEXT NOT NULL,
        ubicacion_id INTEGER NOT NULL, material TEXT NOT NULL, codigo_material TEXT NOT NULL DEFAULT '',
        palets INTEGER NOT NULL DEFAULT 0, unidades_por_palet INTEGER NOT NULL DEFAULT 1,
        unidades_sueltas INTEGER NOT NULL DEFAULT 0, referencia TEXT, albaran_id INTEGER,
        FOREIGN KEY (ubicacion_id) REFERENCES almacen_ubicaciones(id)
    )""")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_almacen_stock_ubicacion ON almacen_stock(ubicacion_id)")
    cur.execute("CREATE INDEX IF NOT EXISTS idx_almacen_movimientos_fecha ON almacen_movimientos(fecha)")
    _seed_almacen_secciones(connection)
    connection.commit()


def _connect():
    if DATABASE_URL:
        import psycopg2

        return PostgresConnection(psycopg2.connect(DATABASE_URL))

    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    return sqlite3.connect(DB_PATH, check_same_thread=False)


def init_db():
    global _DB_INITIALIZED

    if _DB_INITIALIZED:
        return
    with _DB_INIT_LOCK:
        if _DB_INITIALIZED:
            return
        conn = _connect()
        try:
            if DATABASE_URL:
                _init_postgres(conn)
            else:
                _init_sqlite(conn)
            _DB_INITIALIZED = True
        finally:
            conn.close()


def get_conn():
    init_db()
    return _connect()
